SWAP_HANDS_ENABLE     = no
AUTOCORRECTION_ENABLE = yes
CAPS_WORD_ENABLE      = yes
CONSOLE_ENABLE        = yes
KEYLOGGER_ENABLE      = no
WPM_ENABLE            = yes



DYNAMIC_MACRO_ENABLE = yes 

EXTRAFLAGS += -flto